apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  ports:
  - name: metrics
    port: 10249
    protocol: TCP
    targetPort: 10249
  selector:
    component: kube-proxy
  type: ClusterIP