apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: datapf-mgt
  namespace: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector: 
    matchLabels:
      metrics: node
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml