apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: datapf-mgt