apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: master
  namespace: prometheus
spec:
  replicas: 3
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  ruleSelector: {}
  podMonitorSelector: {}
  probeSelector: {}